### ISSUE TITLE
1.15

### ISSUE THREAD

**Issue by Craluminum2413** [DArkHekRoMaNT/SimpleElevator#1]
**Game Version:** 1.15.0-pre.3
**Mod Version:** 1.1.1
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.15.0-pre.3 (Unstable)06/10/2021 12:29:59: Critical error occurred
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.CollectibleObject.Attributes'.
   at SimpleElevator.BlockElevator.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_6iU9DTCbzMrbDiciwm8GRyl3Mim packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _cj3yxhUHm1vITNT26m9tq8zq7lC._LcGp6vp0iU0HbJoKtBq1oH3wJGn(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._PeuIqQzFn7JdsiaCMO1A0nOHYOF(Single )
   at _myXzIvBGuHgNhKsWypGDvkNbw4X._12elMOUbssfuqzUtVoRc599RYNW(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _UwTpwIUKuzIrz4lc7aDEDr1w32f._ouD1c39oCQ2Eda0lkC3EXYeZtC7(_OdfjAwaG2wGU12XuYVt4myQv5bF , String[] )
   at _j9Ke4RlHC2L45ChATqqx7RI91CC._ouD1c39oCQ2Eda0lkC3EXYeZtC7(ThreadStart )
```

**Comment by DArkHekRoMaNT** [comment]
Fixed in 1.2.0
